# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "6.0"

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm version
  - npm install npm@latest
  - npm install

cache:
  - '%APPDATA%\npm-cache'

build_script:
  - cmd: npm run build

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm run test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
