version: 2
jobs:
  build:
    working_directory: ~/stencil
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
      # Unzip the browserstack binary file
      - run: unzip BrowserStackLocal-linux-x64.zip
      # Run the file with your access key
      - run: ./BrowserStackLocal -k $BROWSER_STACK_ACCESS_KEY

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm install npm@latest
      - run: npm run build
      - run: npm run test.jest -- --maxWorkers=4
      - run: cd test/karma && npm install
      - run: npm run karma.prod
