name: Lint and Format Stencil (Check)

on:
  merge_group:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  format:
    name: Check
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ESLint
        run: npm run lint

      - name: Prettier Check
        run: npm run prettier.dry-run
        shell: bash

      - name: Spellcheck
        run: npm run spellcheck
